/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cpp.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/assets/models/cpp.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.66, -0.16, 0.5]} rotation={[-1.57, 0, -1.67]} scale={[1, 0.15, 1]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.003']} />
        <lineSegments geometry={nodes.Cylinder001_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Text.geometry} material={materials['Material.004']} position={[0.73, 0.55, -0.45]} rotation={[-3.14, 0, 3.11]} scale={[1.42, 17.69, 1.42]} />
        <mesh geometry={nodes.Text001.geometry} material={materials['Material.004']} position={[-0.05, 0.81, -0.19]} rotation={[-3.14, 0, 3.11]} scale={[0.66, 6.48, 0.66]} />
        <mesh geometry={nodes.Text002.geometry} material={materials['Material.004']} position={[-0.05, 0.81, -0.19]} rotation={[-3.14, 0, 3.11]} scale={[0.66, 6.48, 0.66]} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/cpp.glb')
