/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 csharp.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/csharp.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, -1.04, 0]} scale={[1, 0.14, 1]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} position={[-0.09, 0.03, 0.11]} rotation={[1.57, 0, 0]} scale={1.44} />
      <mesh geometry={nodes.Text001.geometry} material={nodes.Text001.material} position={[0.45, -0.06, 0.21]} rotation={[Math.PI / 2, 0, 0]} scale={0.5} />
    </group>
  )
}

useGLTF.preload('/csharp.glb')
