/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 dotnet.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/portfolio/assets/models/dotnet.glb')
  return (
    <group {...props} dispose={null} position={[0, 0, 0]}>
      <group position={[0.07, -0.19, 0.38]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.1, 0.01, 0.1]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} position={[0.08, -0.2, 0.46]} rotation={[Math.PI / 2, 0, -1.57]} scale={[0.07, 0.09, 0.09]} />
      <mesh geometry={nodes.Text001.geometry} material={nodes.Text001.material} position={[0.09, -0.24, 0.42]} rotation={[Math.PI / 2, 0, -1.57]} scale={0.038} />
    </group>
  )
}

useGLTF.preload('/portfolio/assets/models/dotnet.glb')
