/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 js.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/portfolio/assets/models/js.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.11, 0.4, 0.61]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.16, 0.14, 0.14]}>
        <mesh geometry={nodes.Text_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Text_2.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/portfolio/assets/models/js.glb')
