/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 php.glb
*/

import React, { useRef } from "react";
import { Center, useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/portfolio/assets/models/php.glb");
  return (
    <group {...props} dispose={null}>
      <Center scale={1.2}>
        <group
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[-0.11, -0.01, -0.06]}
        >
          <mesh
            geometry={nodes.Cylinder001.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Cylinder001_1.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            geometry={nodes.Cylinder001_2.geometry}
            material={materials["Material.003"]}
          />
        </group>
      </Center>
    </group>
  );
}

useGLTF.preload("/portfolio/assets/models/php.glb");
