/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 python.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/assets/models/python.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.06, -1.85, 1]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/python.glb')
