/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 sql.glb
*/

import React, { useRef } from "react";
import { useGLTF, Center } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/portfolio/assets/models/sql.glb");
  return (
    <group {...props} dispose={null}>
      <Center scale={0.7}>
        <group position={[-0.32, 3.05, 0]} scale={[0.08, 0.006, 0.08]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder007_1.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder007_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
      </Center>
    </group>
  );
}

useGLTF.preload("/portfolio/assets/models/sql.glb");
